services:
  {{APP_NAME}}:
    build: .
    image: app-aesiron-{{APP_NAME}}
    container_name: app-aesiron-{{APP_NAME}}
    volumes:
      - ./app:/app
    ports:
      - "{{PORT}}:{{PORT}}"
    env_file:
      - .env
    networks:
      - aesiron-net

networks:
  aesiron-net:
    external: true
